<a href="https://colab.research.google.com/github/alijonovanargiza28/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [5]:
print(pd.__version__)

2.2.3

In [11]:
mydataset ={
    'cars':["BMW", "Volvo", "Ford", "Tesla", "Ford"],
    'counts':[3,5,7,4,5]
}
df = pd.DataFrame(mydataset)
print(df)

    cars  counts
0    BMW       3
1  Volvo       5
2   Ford       7
3  Tesla       4
4   Ford       5

In [14]:
df.head()

    cars  counts
0    BMW       3
1  Volvo       5
2   Ford       7
3  Tesla       4
4   Ford       5

In [17]:
df.tail(-1)

    cars  counts
1  Volvo       5
2   Ford       7
3  Tesla       4
4   Ford       5

In [18]:
df.shape

(5, 2)

In [21]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [22]:
df.dtypes

cars      object
counts     int64
dtype: object

In [25]:
df.describe(include="all") #numerical colums only

        cars   counts
count      5  5.00000
unique     4      NaN
top     Ford      NaN
freq       2      NaN
mean     NaN  4.80000
std      NaN  1.48324
min      NaN  3.00000
25%      NaN  4.00000
50%      NaN  5.00000
75%      NaN  5.00000
max      NaN  7.00000

In [29]:
df.iloc[1:4]

    cars  counts
1  Volvo       5
2   Ford       7
3  Tesla       4

In [32]:
df.loc[:,"cars"]

0      BMW
1    Volvo
2     Ford
3    Tesla
4     Ford
Name: cars, dtype: object

In [34]:
print(df)

    cars  counts
0    BMW       3
1  Volvo       5
2   Ford       7
3  Tesla       4
4   Ford       5

In [44]:
df [df["counts"] == 5]

    cars  counts
1  Volvo       5
4   Ford       5

In [45]:
#df.mean(numeric_only = True)
df["counts"].mean()

np.float64(4.8)

In [46]:
df.sum()

cars      BMWVolvoFordTeslaFord
counts                       24
dtype: object

In [47]:
df.min()

cars      BMW
counts      3
dtype: object

In [48]:
df.max()

cars      Volvo
counts        7
dtype: object

In [49]:
df.median(numeric_only=True)

counts    5.0
dtype: float64

In [50]:
df.count()

cars      5
counts    5
dtype: int64

In [51]:
df.std(numeric_only=True)

counts    1.48324
dtype: float64

In [63]:
data_with_missing ={
    "cars":["BMW","Volvo",6,"Tesla","Ferrari", None, "Ford"],
    "counts":[3,5,None, 5,3,None,5]
}
df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     5.0
2        6     NaN
3    Tesla     5.0
4  Ferrari     3.0
5     None     NaN
6     Ford     5.0

In [62]:
df_missing.isnull().sum()

cars      1
counts    2
dtype: int64

In [61]:
df_missing.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [ ]:
df_missing.dropna(how="all")

In [64]:
df_missing.dropna(subset=['cars'])

      cars  counts
0      BMW     3.0
1    Volvo     5.0
2        6     NaN
3    Tesla     5.0
4  Ferrari     3.0
6     Ford     5.0

In [66]:
df_missing.fillna(0)

      cars  counts
0      BMW     3.0
1    Volvo     5.0
2        6     0.0
3    Tesla     5.0
4  Ferrari     3.0
5        0     0.0
6     Ford     5.0

In [69]:
df_missing.fillna({"cars":"unknown", "counts":0})

      cars  counts
0      BMW     3.0
1    Volvo     5.0
2        6     0.0
3    Tesla     5.0
4  Ferrari     3.0
5  unknown     0.0
6     Ford     5.0

In [79]:
# df = pd.read_csv("Titanic-Dataset.csv")


df = pd.read_excel("test.xlsx")
df.tail()
#df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [78]:
df.to_excel("test.xlsx")

In [80]:
#Series => 1D
cars = pd.Series(["BMW","Tesla","Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [81]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', 6, 'Tesla', 'Ferrari', None, 'Ford']